### PR TITLE
Finished eslint setup

### PR DESCRIPTION
**Pull request by CreeperPlanet26**
Please review the eslint setup and do you like the rules. Are there any other rules you want me to add? The eslint file is .eslintrc.json

### CODE REVIEW

**Comment by CreeperPlanet26** [comment]
What rules do u have when you code. Do u like semi colons? Do u like to have single quotes or double quotes?

**Comment by CreeperPlanet26** [comment]
Also do u prefer single or double quotes?

**Comment by Maxisthemoose** [comment]
> What rules do u have when you code. Do u like semi colons? Do u like to have single quotes or double quotes?

I learned to always use semi colons, even though JavaScript doesn't need them, I learned that it was good practice to use them anyways.


> Also do u prefer 2 or 4 indention?

In what context? For what?

**Comment by CreeperPlanet26** [comment]
4 spaces is a tab and 2 spaces is a half a tab. Right now its 4 spaces aka a tab.

**Comment by Maxisthemoose** [comment]
Oh ok, yeah tab, I always use a full tab, looks much cleaner in my opinion

**Comment by CreeperPlanet26** [comment]
Would you like me to change it to double quotes its currently single?
Also the semicolon are currently not wanted do u want it?

**Comment by Maxisthemoose** [comment]
I'm fine with either single quotes or double quotes, so I don't really mind, and not having the semi colon for me is fine too, I just learned that it was good practice

**Comment by CreeperPlanet26** [comment]
ok i have added the double quotes and semi colon rules as they are better practice

**Comment by Maxisthemoose** [comment]
Alright, sounds good

**Comment by CreeperPlanet26** [comment]
Does it let you merge the PR?

**Pull request merged**
